keys:
  - &admin_daf age1rafskpaqudsd8vnvcdryt5uqn5lxs4wx22n355h64qv7yg2ya4esr4e7kw
  - &user_daf_daftop age1xv0yq7ppjmvsvmc5na3ha5eue44syvuc024n7ynhufnje8nmzvlqps77zs
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_daf
  - path_regex: secrets/daftop/daf/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_daf
          - *user_daf_daftop
  - path_regex: secrets/daf/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_daf
          - *user_daf_daftop
