{
  lib,
  config,
  namespace,
  pkgs,
  ...
}:

let
  inherit (lib) mkEnableOption mkIf types;
  inherit (lib.${namespace}) mkOpt;

  cfg = config.${namespace}.services.wishlist;
in
{

  options.${namespace}.services.wishlist = {
    enable = mkEnableOption "Whether or not to configure wishlist.";
    base-url = mkOpt types.str "https://wishlist.daftdaf.dev" "The base url";
    port = mkOpt types.int 9050 "The port";
  };

  config = mkIf cfg.enable {
    virtualisation.oci-containers.containers."wishlist" = {
      image = "ghcr.io/cmintey/wishlist:latest";
      environment = {
        "ORIGIN" = cfg.base-url;
        "TOKEN_TIME" = "72";
        "DEFAULT_CURRENCY" = "EUR";
      };
      volumes = [
        "/var/lib/wishlist/data:/usr/src/app/data:rw"
        "/var/lib/wishlist/uploads:/usr/src/app/uploads:rw"
      ];
      ports = [
        "${toString cfg.port}:3280/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=wishlist"
        "--network=wishlist_default"
      ];
    };
    systemd.services."podman-wishlist" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "no";
      };
      after = [
        "podman-network-wishlist_default.service"
      ];
      requires = [
        "podman-network-wishlist_default.service"
      ];
      partOf = [
        "podman-compose-wishlist-root.target"
      ];
      wantedBy = [
        "podman-compose-wishlist-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-wishlist_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f wishlist_default";
      };
      script = ''
      podman network inspect wishlist_default || podman network create wishlist_default
    '';
      partOf = [ "podman-compose-wishlist-root.target" ];
      wantedBy = [ "podman-compose-wishlist-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-wishlist-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };

    services.caddy.virtualHosts = {
      "${cfg.base-url}".extraConfig = ''
          reverse_proxy "http://0.0.0.0:${toString cfg.port}"
          import cloudflare
        '';

        "liste.daftdaf.dev".extraConfig = ''
          redir ${cfg.base-url}
          import cloudflare
        '';
    };

    systemd.tmpfiles.rules = [
      "d /var/lib/wishlist 0775 root root -"
      "d /var/lib/wishlist/data 0775 root root -"
      "d /var/lib/wishlist/uploads 0775 root root -"
    ];
  };
}
