{
  lib,
  config,
  namespace,
  pkgs,
  ...
}:

let
  inherit (lib.${namespace}) mkBoolOpt mkOpt;
  inherit (lib) mkEnableOption mkIf types getExe;

  cfg = config.${namespace}.services.calibre-web-automated;
  username = config.${namespace}.user.name;
in
{

  options.${namespace}.services.calibre-web-automated = {
    enable = mkEnableOption "Whether or not to configure calibre-web-automated.";

    base-url = mkOpt types.str "calibre.daftdaf.dev" "The base url";
    port = mkOpt types.int 8021 "The port";
  };

  config = mkIf cfg.enable {
    virtualisation.oci-containers.containers."calibre-web-automated" = {
      image = "crocodilestick/calibre-web-automated:latest";
      environment = {
        "NETWORK_SHARE_MODE" = "false";
        "PGID" = "1000";
        "PUID" = "1000";
        "TZ" = "CET";
      };
      volumes = [
        "/var/lib/calibre-web-automated:/config:rw"
        "/mnt/livres:/calibre-library:rw"
        "/home/daf/stacks/shelfmark/books:/cwa-book-ingest:rw"
      ];
      ports = [
        "${toString cfg.port}:8083/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=calibre-web-automated"
        "--network=calibre-web-automated_default"
      ];
    };
    systemd.services."podman-calibre-web-automated" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-calibre-web-automated_default.service"
      ];
      requires = [
        "podman-network-calibre-web-automated_default.service"
      ];
      partOf = [
        "podman-compose-calibre-web-automated-root.target"
      ];
      wantedBy = [
        "podman-compose-calibre-web-automated-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-calibre-web-automated_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f calibre-web-automated_default";
      };
      script = ''
      podman network inspect calibre-web-automated_default || podman network create calibre-web-automated_default
    '';
      partOf = [ "podman-compose-calibre-web-automated-root.target" ];
      wantedBy = [ "podman-compose-calibre-web-automated-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-calibre-web-automated-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };

    services.caddy.virtualHosts = {
      "${cfg.base-url}".extraConfig = ''
          reverse_proxy http://127.0.0.1:10080
          import cloudflare
        '';
        "book.daftdaf.dev".extraConfig = ''
          reverse_proxy "http://0.0.0.0:${toString cfg.port}"
          import cloudflare
        '';
        "livre.daftdaf.dev".extraConfig = ''
          reverse_proxy "http://0.0.0.0:${toString cfg.port}"
          import cloudflare
        '';
        "kobo.daftdaf.dev".extraConfig = ''
          redir https://send.djazz.se
          import cloudflare
        '';
    };

    systemd.tmpfiles.rules = [
      "d /var/lib/calibre-web-automated/ 0775 calibre calibre - -"
    ];
  };
}
