plop: ENC[AES256_GCM,data:zTb+662UMys=,iv:FoWLQTCKoWmXHiIrpX/37IEVSffdnhM3uj0fnYyvSyc=,tag:8lvP9cN33TtvUC7QBluDeQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rafskpaqudsd8vnvcdryt5uqn5lxs4wx22n355h64qv7yg2ya4esr4e7kw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTWl1TStFUHpFN1hIS2Fl
        L3dPTUhPeVlOeHNVUUJ4UWwrckVJT0p4NFZZCjhpVHB5TlAyNFpzQzhVVVdMTmUr
        dEc5dmRRRURpWDB6VlpSVEJ3M0hJZk0KLS0tIEZGYmFtU0Rody9nNkJkNW9lYXZ4
        VEd6a0pXUExZNkM2dnNLWVZHZ21IMlUK5HiF1oheKxQLcuAv+/GSMXGRVAjFq+UJ
        WbkWJ6qbXoAlllL4XO9ABOquoik24ULhyHSDthIx+En8eAG914gQHA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1xv0yq7ppjmvsvmc5na3ha5eue44syvuc024n7ynhufnje8nmzvlqps77zs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNUo1RW80RFROY3MrekFF
        eXRid0x6eXQ5RzlycWN2dkdXOVk0Z3JVdHhrClo1eDBXYUs4NjFkME5wYmhuN3Y1
        SnJESkFDQVlQV1AxVWV4cmpnMm9FV0UKLS0tIGpIMjhFa0pGWW94U3dJcHBtd3Mv
        RjZxUUZKdDdIWHRyOVFNemlzd0lUTnMK71DVWCqvBe7kQfpGk3U2/0TZKhg+J4kT
        deXvDWn1aAQV3BC/KP3XSVE2fpxtrkw10Dd+67l+9Lggm6UidO4Nhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-25T11:31:00Z"
  mac: ENC[AES256_GCM,data:UwvWjjZ0fBG06IiCCvcQF80+kseHxsglrzGvWPjFdo4gjK0VQJJv8W9E0dzEBGjD3T9q9+3N5kYm1TSpq+8nlG+2/gs0kbeUJ+bm+xpxU+K6/Y6LGduow6SBDfQtpyG8c3VQg6/MbFlFaWLC+oM9WYE5UlP8ZHUbE84nextzOHU=,iv:lzJ5Yz4qRUlyyXlRhBR2LaRWU+zMgNEyPWPXPNqzllE=,tag:i1Ken439U7pTqjPRG9NEmg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.2
