example_key: ENC[AES256_GCM,data:n/6TeQlU/NOgwcte3w==,iv:nZlCRkGZHbxxt/ISWFl+gjhfSH+GS91S7y5avyN+sa0=,tag:MUne0zw3J+Muby7Cdovwzg==,type:str]
myservice:
  mysubdir:
    mysecret: ENC[AES256_GCM,data:+UQpbv6I3o9v,iv:Ln9qHvtRUZXpufKUlY4D5iEXFs+eZF3R9XkQkWZsetY=,tag:g8IetEbF+fCcknmpH+37sA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rafskpaqudsd8vnvcdryt5uqn5lxs4wx22n355h64qv7yg2ya4esr4e7kw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TDdwZ3JrSlpkVkxpWmNj
        d3hEZ2NOeHFTdFVhSS9PejQrZFZYWDU4TUIwCkFZbklUam55NU5ramdZTC83Ym53
        Ym5pUnZmQm9WNENhZkRPaWlIMTBiNEEKLS0tIGhkcXhsZDhqblhGTFVMekljQmx5
        ZGNUNWJ3MlR5d3c0ZlU1Skk3L1R4QlEKL48oTzyj4XU/gAQrrr34JsulXUebst60
        vixqiaKu3NQsrPRzu3OEmwZs4SwDaw6q8qiF68k3IqQt5I7a2SUFIw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1xv0yq7ppjmvsvmc5na3ha5eue44syvuc024n7ynhufnje8nmzvlqps77zs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bE5uQjlZZDg1VGcrc3FS
        eXkxNGNXQnBBYk9NbHhvMTJZRHpmN2hkSTBnClRmUlJ4YzBEQjdsOXlDaVl3aWFk
        S3k0N2JEdnBxekRmQnZER3ZDMi9SdEkKLS0tIGhVNENYNFBjcStZemNtNW9aQ0l4
        T1BiYWIyaENaYm1YcHlGWVpkZUUrbDAKTsr+UoH70kOLt+KjGOBJ82S7d3xofTy7
        NF6DJ6N8nS4leIw4GDMUNvD58oGfyjk5QPZhOXbsbhT63XNg3csdAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-25T10:50:13Z"
  mac: ENC[AES256_GCM,data:7JSMjQSNtJnL9joCsrgurSII2i/6TsAwCi0ylSQLEciwp3r9g/nL0YQV82GBoC15TS5JgvzsrbwWC3dXD0PaJaCoDm/iGSzlsAlkSpBO6AGchf2E/oVdawFCQ8Gae+eykjQLFhMkuzvRxVkta3yaP+78H6USziLMG6ixDIYKJ/s=,iv:w2wOzBNFyeG3riVYcjg+LM+g/YG6Rx7XSJzTpvrEAsc=,tag:jiWpczVYzYgPMUVMtfoONQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.2
