# Nightly encrypted restic backups of the state that cannot be regenerated.
# See ./README.md. dafoltop backs up to its own dock disk; dafpi to
# dafoltop's rest-server (the backup-server aspect), append-only.
{ inputs, ... }:
{
  flake.modules.nixos.backup =
    {
      lib,
      config,
      pkgs,
      ...
    }:

    let
      inherit (lib)
        mkIf
        mkOption
        optionals
        optionalString
        types
        ;
      opt =
        type: default: description:
        mkOption { inherit type default description; };

      cfg = config.dafos.services.backup;

      user = config.dafos.user.name;
      home = "/home/${user}";
      host = config.networking.hostName;
      alerting = config.dafos.services.alerting.enable or false;
      localRepository = lib.hasPrefix "/" cfg.repository;

      # Written by the backup-dumps aspect (as the user, because the databases
      # live in rootless containers). Immich's database is dumped here in the
      # prepare step instead: it is a native service owned by postgres.
      userDumps = "${home}/backup-staging/current";
      rootDumps = "/var/lib/backup-staging";

      immich = config.services.immich;

      paths = [
        userDumps
        rootDumps
        "${home}/stacks"
      ]
      ++ cfg.extraPaths
      ++ [
        # What decrypts the secrets on a rebuilt host: restoring these before the
        # first boot keeps every system secret readable (see secrets/AGENTS.md).
        "${home}/.config/sops/age"
        "${home}/.ssh/daf@${host}.pem"
        "/etc/ssh/ssh_host_ed25519_key"
        "/etc/ssh/ssh_host_ed25519_key.pub"
        "/etc/ssh/ssh_host_rsa_key"
        "/etc/ssh/ssh_host_rsa_key.pub"
      ]
      ++ optionals immich.enable [
        # Originals only: thumbs/ and encoded-video/ are regenerated, backups/ is
        # replaced by the dump above.
        "/var/lib/immich/upload"
        "/var/lib/immich/library"
        "/var/lib/immich/profile"
      ]
      ++ optionals config.services.home-assistant.enable [ "/var/lib/hass" ]
      ++ optionals config.services.zigbee2mqtt.enable [ "/var/lib/zigbee2mqtt" ]
      ++ optionals config.services.mosquitto.enable [ "/var/lib/mosquitto" ]
      ++ optionals config.services.tailscale.enable [ "/var/lib/tailscale" ];

      exclude = [
        # Home Assistant: the recorder database is history (graphs, statistics) and
        # about 3 GB of constantly rewritten SQLite. Registries, helpers and the
        # UI-made automations are what must survive.
        "/var/lib/hass/home-assistant_v2.db*"
        "/var/lib/hass/home-assistant.log*"
        "/var/lib/hass/deps"
        "/var/lib/hass/tts"
        "/var/lib/hass/backups"
        "/var/lib/zigbee2mqtt/log"
        # Database servers cannot be copied consistently while they run; their
        # dumps (userDumps, rootDumps) are the backup of record.
        "${home}/stacks/*/postgres"
        "${home}/stacks/bookorbit/db"
        "${home}/stacks/grimmory/db"
        # Regenerated by the apps.
        "${home}/stacks/**/cache"
        "${home}/stacks/**/transcodes"
        "${home}/stacks/**/logs"
        "${home}/stacks/**/MediaCover"
        "${home}/stacks/**/trickplay"
        "**/__pycache__"
      ];
    in
    {
      options.dafos.services.backup = {
        enable = lib.mkEnableOption "nightly encrypted restic backups of the state that cannot be regenerated";

        repository =
          opt types.str "/mnt/backup/restic"
            "Where the restic repository lives: a local path, or a rest: URL.";
        time = opt types.str "03:30" "When the backup runs (after the dumps, 03:00 by default).";
        extraPaths = opt (types.listOf types.str) [ ] "Host-specific paths to back up as well.";
        passwordSopsFile = opt types.path (
          inputs.self + "/secrets/dafoltop/restic.yaml"
        ) "sops file holding restic/password for this host's repository.";
        environmentFile =
          opt (types.nullOr types.str) null
            "Extra environment for restic (e.g. RESTIC_REST_USERNAME / RESTIC_REST_PASSWORD).";
        prune =
          opt types.bool true
            "Whether this host applies the retention itself (not possible on an append-only rest-server).";
      };

      config = mkIf cfg.enable {
        # Generated once and kept only in sops. It is not recoverable from the
        # repository: keep a copy outside this host too (a password manager).
        sops.secrets."restic/password".sopsFile = cfg.passwordSopsFile;

        # The mount point must exist even when the disk does not.
        systemd.tmpfiles.rules = mkIf localRepository [ "d ${dirOf cfg.repository} 0755 root root -" ];

        services.restic.backups.local = {
          inherit (cfg) repository environmentFile;
          inherit paths exclude;
          initialize = true;
          passwordFile = config.sops.secrets."restic/password".path;

          timerConfig = {
            OnCalendar = cfg.time;
            Persistent = true;
            RandomizedDelaySec = "5m";
          };

          pruneOpts = optionals cfg.prune [
            "--keep-daily 7"
            "--keep-weekly 4"
            "--keep-monthly 6"
          ];

          # Reads 2 % of the pack data back every run, so the whole repository has
          # been verified a few times a year without a nightly full read.
          runCheck = true;
          checkOpts = [ "--read-data-subset=2%" ];

          extraBackupArgs = [ "--exclude-caches" ];
          inhibitsSleep = true;

          backupPrepareCommand = ''
            set -eu
            ${pkgs.coreutils}/bin/install -d -m 0700 ${rootDumps}
            ${optionalString immich.enable ''
              ${pkgs.util-linux}/bin/runuser -u postgres -- \
                ${config.services.postgresql.package}/bin/pg_dump -Fc ${immich.database.name} \
                > ${rootDumps}/immich.dump.tmp
              ${pkgs.coreutils}/bin/mv ${rootDumps}/immich.dump.tmp ${rootDumps}/immich.dump
            ''}
            # A stale dump must not stop the files from being backed up, but it must
            # not pass quietly either.
            if ! ${pkgs.findutils}/bin/find ${userDumps} -maxdepth 0 -mmin -1560 2>/dev/null | ${pkgs.gnugrep}/bin/grep -q .; then
              echo "container database dumps are missing or older than 26 h" >&2
              ${optionalString alerting "/run/current-system/sw/bin/dafos-alert 'Backup' 'Container database dumps are missing or stale; files are still being backed up.' || true"}
            fi
          '';
        };

        systemd.services.restic-backups-local = {
          # Fails (and alerts) when the disk is absent, instead of initialising a
          # repository on the NVMe root underneath an empty mount point.
          unitConfig.RequiresMountsFor = mkIf localRepository [ cfg.repository ];
          serviceConfig = {
            Nice = 10;
            IOSchedulingClass = "idle";
          };
          onFailure = optionals alerting [ "alert-failure@%n.service" ];
        };
      };
    };
}
