{
  flake.modules.nixos.nix =
    {
      config,
      pkgs,
      lib,
      ...
    }:

    let
      inherit (lib)
        mkIf
        mkOption
        types
        optional
        mapAttrsToList
        ;
      cfg = config.dafos.nix;
      max-jobs-type = with types; either int (enum [ "auto" ]);
      substituters-submodule = types.submodule (_: {
        options = with types; {
          key = mkOption {
            type = nullOr str;
            default = null;
            description = "The trusted public key for this substituter.";
          };
        };
      });
    in
    {
      options.dafos.nix = with types; {
        enable = mkOption {
          type = bool;
          default = true;
          description = "Whether or not to manage nix configuration.";
        };
        nh.enable = lib.mkEnableOption "nh";
        package = mkOption {
          type = package;
          default = pkgs.nixVersions.latest;
          description = "Which nix package to use.";
        };

        # Build parallelism, per host. The defaults mirror nix's own — one job per
        # logical core, every core handed to each build — which is what you want on
        # a desktop and far too greedy on a small box that is also serving
        # something. nh has no knob of its own here; it shells out to nix, so these
        # cover nh, nixos-rebuild and deploy-rs alike.
        max-jobs = mkOption {
          type = max-jobs-type;
          default = "auto";
          description = "How many derivations nix builds at once (nix.conf max-jobs).";
        };
        cores = mkOption {
          type = int;
          default = 0;
          description = "How many cores nix hands to an individual build (nix.conf cores); 0 means all of them.";
        };

        # A trusted user can pass any setting to the daemon and import unsigned
        # paths, which makes it root-equivalent without going through sudo.
        trust-user = mkOption {
          type = bool;
          default = true;
          description = "Whether the main user is a nix trusted-user. A host that turns this off only accepts deploys whose paths are signed by a key in signing.trusted-keys.";
        };

        signing = {
          secret-key-file = mkOption {
            type = nullOr str;
            default = null;
            description = "Key this host signs every path it builds with. Generated by hand on the host; never in the repo.";
          };
          trusted-keys = mkOption {
            type = listOf str;
            default = [ ];
            description = "Public keys of other hosts' signing keys whose paths this host accepts.";
          };
        };

        default-substituter = {
          url = mkOption {
            type = str;
            default = "https://cache.nixos.org";
            description = "The url for the substituter.";
          };
          key = mkOption {
            type = str;
            default = "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=";
            description = "The trusted public key for the substituter.";
          };
        };

        extra-substituters = mkOption {
          type = attrsOf substituters-submodule;
          default = {
            "https://nix-community.cachix.org" = {
              key = "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=";
            };
            "https://nix-gaming.cachix.org" = {
              key = "nix-gaming.cachix.org-1:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4=";
            };
            "https://niri-epireyn.cachix.org" = {
              key = "niri-epireyn.cachix.org-1:tlVyFN7CtsDT+ZcLPS+ekFWeT1X6X4OqvWqbBMyIzFA=";
            };
            "https://vicinae.cachix.org" = {
              key = "vicinae.cachix.org-1:1kDrfienkGHPYbkpNj1mWTr7Fm1+zcenzgTizIcI3oc=";
            };
          };
          description = "Extra substituters to configure.";
        };
      };

      config = mkIf cfg.enable {
        assertions = mapAttrsToList (name: value: {
          assertion = value.key != null;
          message = "dafos.nix.extra-substituters.${name}.key must be set";
        }) cfg.extra-substituters;

        environment.systemPackages = with pkgs; [
          deploy-rs
          flake-checker
          nil
          nix-index
          nix-init
          nix-output-monitor
          nix-prefetch-git
          yaml2nix
        ];

        programs.nh = mkIf cfg.nh.enable {
          enable = true;
          clean = {
            enable = true;
            extraArgs = "--keep 15 --keep-since 14d";
            dates = "weekly";
          };
        };

        nix =
          let
            users = [
              "root"
              config.dafos.user.name
            ]
            ++ optional config.services.hydra.enable "hydra";

            trusted = [
              "root"
            ]
            ++ optional cfg.trust-user config.dafos.user.name
            ++ optional config.services.hydra.enable "hydra";
          in
          {
            inherit (cfg) package;

            settings = {
              experimental-features = [
                "nix-command"
                "flakes"
                "pipe-operators"
              ];
              inherit (cfg) max-jobs cores;
              http-connections = 50;
              warn-dirty = false;
              log-lines = 50;
              sandbox = "relaxed";
              auto-optimise-store = true;
              trusted-users = trusted;
              allowed-users = users;

              substituters = [
                cfg.default-substituter.url
              ]
              ++ (mapAttrsToList (name: _value: name) cfg.extra-substituters);
              trusted-public-keys = [
                cfg.default-substituter.key
              ]
              ++ (mapAttrsToList (_name: value: value.key) cfg.extra-substituters)
              ++ cfg.signing.trusted-keys;
            }
            // lib.optionalAttrs (cfg.signing.secret-key-file != null) {
              secret-key-files = [ cfg.signing.secret-key-file ];
            };

            gc = mkIf (!cfg.nh.enable) {
              automatic = true;
              dates = "weekly";
              options = "--delete-older-than 30d";
            };

            # flake-utils-plus (vendored in _compat/fup-options.nix)
            generateRegistryFromInputs = true;
            generateNixPathFromInputs = true;
            linkInputs = true;
          };
      };
    };
}
