{
  flake.modules.nixos.sops =
    {
      config,
      lib,
      ...
    }:

    let
      inherit (lib) mkOption types;

      cfg = config.dafos.security.sops;
    in
    {
      options.dafos.security.sops = {
        enable = lib.mkEnableOption "sops";
        defaultSopsFile = mkOption {
          type = types.path;
          default = null;
          description = "Default sops file.";
        };
        # System-level secrets are decrypted with the host SSH key, whose derived
        # age identity is the `root_<host>` key authorized in .sops.yaml.
        sshKeyPaths = mkOption {
          type = types.listOf types.path;
          default = [ "/etc/ssh/ssh_host_ed25519_key" ];
          description = "SSH Key paths to use.";
        };
        # The user identity at ~/.config/sops/age/keys.txt is generated by the
        # home-manager sops module (modules/home/services/sops). On a host
        # without it the file never exists, and sops-install-secrets fails the
        # whole activation on a missing keyFile.
        userKey = mkOption {
          type = types.bool;
          default = true;
          description = "Also decrypt system secrets with the main user's age key (keys.txt).";
        };
      };

      config = lib.mkIf cfg.enable {
        sops = {
          inherit (cfg) defaultSopsFile;

          age = {
            inherit (cfg) sshKeyPaths;

            keyFile = lib.mkIf cfg.userKey "${
              config.users.users.${config.dafos.user.name}.home
            }/.config/sops/age/keys.txt";
          };
        };

        # Declare secrets where this module is enabled, e.g.:
        #   sops.secrets."my_secret".sopsFile = inputs.self + "/secrets/daf/<name>.yaml";
      };
    };

  flake.modules.homeManager.sops =
    {
      config,
      lib,

      pkgs,
      ...
    }:

    let
      inherit (lib) mkIf types;
      opt =
        type: default: description:
        lib.mkOption { inherit type default description; };

      cfg = config.dafos.services.sops;

      ageKeyFile = "${config.home.homeDirectory}/.config/sops/age/keys.txt";

      # snowfall's extended lib does not carry home-manager's `lib.hm`; the DAG
      # helpers are exposed on `config.lib` instead.
      inherit (config.lib) dag;

      # Every file sops-install-secrets writes, as the paths containers reference.
      sopsPaths = lib.unique (
        lib.mapAttrsToList (_: s: toString s.path) config.sops.secrets
        ++ lib.mapAttrsToList (_: t: toString t.path) config.sops.templates
      );

      # Blocks until each path exists and is non-empty. A missing or empty file is
      # read as an empty value: nps's create-extra-files runs `echo "VAR=$(<path)"`,
      # whose failed substitution does not trip errexit.
      waitForSecrets = pkgs.writeShellApplication {
        name = "wait-for-sops-secrets";
        runtimeInputs = [ pkgs.coreutils ];
        text = ''
          timeout=60
          for p in "$@"; do
            [ -s "$p" ] && continue
            echo "waiting for sops-nix to write $p"
            until [ -s "$p" ]; do
              if [ "$SECONDS" -ge "$timeout" ]; then
                echo "$p still missing or empty after ''${timeout}s; is sops-nix.service failing?" >&2
                exit 1
              fi
              sleep 1
            done
          done
        '';
      };
    in
    {
      options.dafos.services.sops = with types; {
        enable = opt bool true "Whether to enable sops.";
        defaultSopsFile = opt path null "Default sops file.";
        sshKeyPaths = opt (listOf path) [ ] "SSH Key paths to use.";
      };

      # On a switch, home-manager's sd-switch starts each new container in its own
      # D-Bus call, before the `sops-nix` activation step writes the new secrets,
      # so a container whose secret was new found no file and nps's
      # create-extra-files turned it into an empty value. Hit 2026-10-07/08 by
      # glance (dafoltop), glance-agent and kitchenowl (dafpi). The podman drop-in
      # below (`Wants=` + `After=sops-nix.service`) runs the decryption first.
      #
      # This wait is the safety net behind it: every container that reads a sops
      # path (extraEnv.fromFile, a volume source) checks those files exist and are
      # non-empty before starting, so a failing sops-nix fails the container
      # instead of handing it empty secrets. It waits (60 s) rather than fails at
      # once: a start job still activating holds its `Requires=` dependents back,
      # a failed one fails them for good. nps's own ExecStartPre
      # (create-extra-files) comes after, hence `mkBefore`.
      options.services.podman.containers = lib.mkOption {
        type = types.attrsOf (
          types.submodule (
            { config, ... }:
            let
              referenced =
                lib.mapAttrsToList (_: v: toString v.fromFile) (
                  lib.filterAttrs (_: v: lib.isAttrs v && (v.fromFile or null) != null) (config.extraEnv or { })
                )
                ++ map (v: lib.head (lib.splitString ":" v)) config.volumes;
              secrets = lib.unique (lib.filter (p: lib.elem p sopsPaths) referenced);
            in
            {
              config = mkIf (cfg.enable && secrets != [ ]) {
                extraConfig.Service.ExecStartPre = lib.mkBefore [
                  "${lib.getExe waitForSecrets} ${lib.escapeShellArgs secrets}"
                ];
              };
            }
          )
        );
      };

      config = mkIf cfg.enable {
        home.packages = with pkgs; [
          age
          sops
          ssh-to-age
          openssl
        ];

        sops = {
          inherit (cfg) defaultSopsFile;
          defaultSopsFormat = "yaml";

          age = {
            # Fallback only, for hosts that declare no sshKeyPaths. sops-nix runs
            # `age-keygen` whenever keyFile is absent, and the identity it invents is
            # authorized nowhere, so the activation step below gets there first.
            generateKey = true;
            keyFile = ageKeyFile;
            # Each host declares its own SSH key in its home config; the derived
            # age identity must be authorized in .sops.yaml.
            inherit (cfg) sshKeyPaths;
          };
        };

        # Keep the age identity the `sops` CLI reads in sync with the one sops-nix
        # actually decrypts with.
        #
        # sops-nix uses two different identities without reconciling them: at
        # activation `sops-install-secrets` derives one from `age.sshKeyPaths`, while
        # the `sops` CLI only ever reads `age.keyFile`. Because `generateKey` fills a
        # missing keyFile with a *random* `age-keygen` identity, a fresh host ends up
        # with working secrets but a CLI that cannot decrypt anything — the identity
        # in keyFile is not the one .sops.yaml authorizes. That is what happened on
        # dafbox (keys.txt generated 2026-02-05, authorized nowhere).
        #
        # Running before the `sops-nix` entry means keyFile already exists by the time
        # sops-nix would generate one, so `generateKey` stays inert on these hosts.
        # The previous file is kept as a timestamped .bak rather than dropped, since
        # an unrecognised identity here might still be someone's only copy.
        home.activation.sopsAgeKeyFromSshKey = mkIf (cfg.sshKeyPaths != [ ]) (
          dag.entryBefore [ "sops-nix" ] ''
            ageKeyFile=${lib.escapeShellArg ageKeyFile}
            derived=""

            for sshKey in ${lib.concatMapStringsSep " " lib.escapeShellArg cfg.sshKeyPaths}; do
              if [ -r "$sshKey" ]; then
                derived="$(${lib.getExe pkgs.ssh-to-age} -private-key -i "$sshKey" 2>/dev/null)" || derived=""
                [ -n "$derived" ] && break
              fi
            done

            if [ -n "$derived" ]; then
              want="$(printf '%s\n' "$derived" | ${pkgs.age}/bin/age-keygen -y /dev/stdin 2>/dev/null)" || want=""
              have=""
              if [ -f "$ageKeyFile" ]; then
                have="$(${pkgs.age}/bin/age-keygen -y "$ageKeyFile" 2>/dev/null)" || have=""
              fi

              if [ -n "$want" ] && [ "$want" != "$have" ]; then
                run ${pkgs.coreutils}/bin/mkdir -p "$(${pkgs.coreutils}/bin/dirname "$ageKeyFile")"

                if [ -f "$ageKeyFile" ]; then
                  run ${pkgs.coreutils}/bin/cp -a "$ageKeyFile" \
                    "$ageKeyFile.bak-$(${pkgs.coreutils}/bin/date +%Y%m%d%H%M%S)"
                fi

                tmp="$(${pkgs.coreutils}/bin/mktemp)"
                ${pkgs.coreutils}/bin/chmod 600 "$tmp"
                printf '%s\n' "$derived" > "$tmp"
                run ${pkgs.coreutils}/bin/mv -f "$tmp" "$ageKeyFile"
                ${pkgs.coreutils}/bin/rm -f "$tmp"

                echo "sops: age identity in $ageKeyFile now derived from $sshKey ($want)"
              fi
            fi
          ''
        );

        # A private key, whichever way it got there: `cp -a` above keeps the mode
        # of whatever it backs up, and dafoltop's keys.txt had been 0644 since it
        # was put there by hand.
        home.activation.sopsAgeKeyPermissions = dag.entryAfter [ "sopsAgeKeyFromSshKey" ] ''
          for f in ${lib.escapeShellArg ageKeyFile} ${lib.escapeShellArg ageKeyFile}.bak-*; do
            [ -f "$f" ] && run ${pkgs.coreutils}/bin/chmod 600 "$f"
          done
          true
        '';

        # Containers read their secrets when they start, and sops-nix.service (a
        # oneshot) is only ordered before the ones that remembered to say so. The rest
        # race it: on 2026-10-01 bar-assistant-meilisearch started 2 s before the
        # secrets existed, exited on an empty master key, and its dependents stayed
        # down. authelia, lldap and immich-kiosk read secrets too.
        #
        # A dash-truncated drop-in applies to every `podman-*.service` unit, present
        # and future, so no list of container names has to be kept in step.
        #
        # `Wants=` too, not only `After=`: on a switch, sd-switch starts the new
        # containers (and waits for them, 2 min by default) before home-manager's
        # `sops-nix` activation step writes the new secrets, so `After=` alone
        # orders against nothing and the wait-for-sops-secrets ExecStartPre above
        # would sit out its 60 s and fail. With `Wants=`, starting a container
        # starts the decryption first, in the same transaction, from the unit
        # files sd-switch has just loaded. The cost: sops-nix (a oneshot, inactive
        # once done) re-runs on every container start, which only rewrites the
        # same files. sd-switch only reads each unit's own `.service.d`, so
        # changing this restarts nothing on a switch.
        xdg.configFile."systemd/user/podman-.service.d/10-after-sops-nix.conf".text = ''
          [Unit]
          Wants=sops-nix.service
          After=sops-nix.service
        '';
      };
    };
}
