{
  flake.modules.nixos.sops =
    {
      config,
      lib,
      ...
    }:

    let
      inherit (lib) mkOption types;

      cfg = config.dafos.security.sops;
    in
    {
      options.dafos.security.sops = {
        enable = lib.mkEnableOption "sops";
        defaultSopsFile = mkOption {
          type = types.path;
          default = null;
          description = "Default sops file.";
        };
        # System-level secrets are decrypted with the host SSH key, whose derived
        # age identity is the `root_<host>` key authorized in .sops.yaml.
        sshKeyPaths = mkOption {
          type = types.listOf types.path;
          default = [ "/etc/ssh/ssh_host_ed25519_key" ];
          description = "SSH Key paths to use.";
        };
        # The user identity at ~/.config/sops/age/keys.txt is generated by the
        # home-manager sops module (modules/home/services/sops). On a host
        # without it the file never exists, and sops-install-secrets fails the
        # whole activation on a missing keyFile.
        userKey = mkOption {
          type = types.bool;
          default = true;
          description = "Also decrypt system secrets with the main user's age key (keys.txt).";
        };
      };

      config = lib.mkIf cfg.enable {
        sops = {
          inherit (cfg) defaultSopsFile;

          age = {
            inherit (cfg) sshKeyPaths;

            keyFile = lib.mkIf cfg.userKey "${
              config.users.users.${config.dafos.user.name}.home
            }/.config/sops/age/keys.txt";
          };
        };

        # Declare secrets where this module is enabled, e.g.:
        #   sops.secrets."my_secret".sopsFile = inputs.self + "/secrets/daf/default.yaml";
      };
    };
}
