{
  lib,
  config,
  namespace,
  pkgs,
  ...
}:

let
  inherit (lib) mkEnableOption mkIf types;
  inherit (lib.${namespace}) mkOpt;

  kiosk-config = "${./config}:/config:rw";
  kiosk-css = "${./css}/custom.css:/custom.css:rw";
  kiosk-weather = "${config.sops.secrets."immich-kiosk-weather-api-key-env".path}:/weather-api.txt:rw";
  cfg = config.${namespace}.services.immich-kiosk;
in
  {
    options.${namespace}.services.immich-kiosk = {
      enable = mkEnableOption "Whether or not to configure immich-kiosk.";
      base-url = mkOpt types.str "https://kiosk.daftdaf.dev" "The base url";
      server-url = mkOpt types.str "https://photos.daftdaf.dev" "The base url";
      port = mkOpt types.int 8085 "The port";
    };

    config = mkIf cfg.enable {
      sops.secrets."immich-kiosk-api-key-env".sopsFile =
        lib.snowfall.fs.get-file "secrets/daf/immich-kiosk.yaml";
      sops.secrets."immich-kiosk-weather-api-key-env".sopsFile =
        lib.snowfall.fs.get-file "secrets/daf/immich-kiosk.yaml";
      sops.secrets."immich-kiosk-albums-key-env".sopsFile =
        lib.snowfall.fs.get-file "secrets/daf/immich-kiosk.yaml";

      virtualisation.oci-containers.containers."immich-kiosk" = {
        image = "ghcr.io/damongolding/immich-kiosk:latest";
        environmentFiles = [
          config.sops.secrets."immich-kiosk-api-key-env".path
          config.sops.secrets."immich-kiosk-albums-key-env".path
        ];
        environment = {
          "LANG" = "fr_FR";
          "TZ" = "Europe/Paris";
          "KIOSK_IMMICH_URL" = cfg.server-url;
          "KIOSK_WEATHER_API_KEY_FILE" = "/weather-api.txt";
        };
        volumes = [
          kiosk-config
          kiosk-css
          kiosk-weather
        ];
        ports = [
          "${toString cfg.port}:3000/tcp"
        ];
        log-driver = "journald";
        extraOptions = [
          "--health-cmd=[\"curl\", \"-f\", \"http://localhost:3000/health\"]"
          "--health-interval=30s"
          "--health-retries=3"
          "--health-start-period=10s"
          "--health-timeout=5s"
          "--network-alias=immich-kiosk"
          "--network=immich-kiosk_default"
        ];
      };
      systemd.services."podman-immich-kiosk" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-immich-kiosk_default.service"
        ];
        requires = [
          "podman-network-immich-kiosk_default.service"
        ];
        partOf = [
          "podman-compose-immich-kiosk-root.target"
        ];
        wantedBy = [
          "podman-compose-immich-kiosk-root.target"
        ];
      };

      # Networks
      systemd.services."podman-network-immich-kiosk_default" = {
        path = [ pkgs.podman ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f immich-kiosk_default";
        };
        script = ''
          podman network inspect immich-kiosk_default || podman network create immich-kiosk_default
        '';
        partOf = [ "podman-compose-immich-kiosk-root.target" ];
        wantedBy = [ "podman-compose-immich-kiosk-root.target" ];
      };

      # Root service
      # When started, this will automatically create all resources and start
      # the containers. When stopped, this will teardown all resources.
      systemd.targets."podman-compose-immich-kiosk-root" = {
        unitConfig = {
          Description = "Root target generated by compose2nix.";
        };
        wantedBy = [ "multi-user.target" ];
      };

      services.caddy.virtualHosts = {
        "${cfg.base-url}".extraConfig = ''
          reverse_proxy "http://0.0.0.0:${toString cfg.port}"
          import cloudflare
        '';
      };
    };
  }
